### ISSUE TITLE
Readme is misleading with regards to withConsulHost

### ISSUE THREAD

**Issue by imavroukakis** [Magnetme/consultant#15]
The README implies that using `withConsulHost` without a port, will default to 8500, which is not the case.

**Comment by michaeldejong** [comment]
Hi @imavroukakis! Thanks for submitting the issue.

Yes, ideally we should indeed default to 8500 if no other port is specified. If you'd like, you can submit a patch, otherwise we'll try to address it before the next release.

**Comment by imavroukakis** [comment]
Will do, thanks.

**Comment by imavroukakis** [comment]
https://github.com/Magnetme/consultant/pull/16

**Comment by michaeldejong** [comment]
Will close this when 1.5.1 is released on monday.

**Comment by michaeldejong** [comment]
#18 Has fixed the remaining edge cases. This has been deployed as of version 1.5.1 which is now available from Maven Central.
