### ISSUE TITLE
Defining port different than 8500

### ISSUE THREAD

**Issue by GarciaPL** [Magnetme/consultant#23]
Hi,

Have you ever thought to put in Consultant builder a way to define port different than 8500 ? Thanks in advance!

**Comment by michaeldejong** [comment]
Hi @GarciaPL!

This is already possible by either:

1. Using the builder: `builder.withConsulHost("http://localhost:8501")`.
2. Or using ENV variables: `CONSUL_HOST=http://localhost:8501`.

**Comment by GarciaPL** [comment]
Hi,

thank you for reply. Yes it works ;) Moreover I was trying to fetch properties from consul which are stored at this moment in directories like dev, qa but invoking getProperties() method returns empty Properties object. Do you have any idea what might be missing ?

**Comment by michaeldejong** [comment]
Ah yes currently Consultant only supports one way of storing/retrieving settings. It only reads/listens to config defined in a particular folder in the root folder, which has to be named after the service name. So if I have a builder like this:

```java
Consultant.builder()
		.identifyAs("some-service")
		.build();
```

Then the config for that service must be placed in a folder called "some-service". We currently don't have a way of conditionally loading settings depending the environment (qa, dev, etc). However it's probably not a good idea anyway to store all of those settings in the same Consul cluster. Instead what we do (which may also be of use to you) is to have separate clusters, each dedicated to their own environment, and containing settings specific to that setting. For development we run Consul in a VM locally, which we also register our services to, so we don't interfere with production or each other.
